### PR TITLE
Switch from github.com/golang/mock to go.uber.org/mock

### PR DESCRIPTION
**Pull request by aruiz14**
## Issue: rancher/rancher#46972

- Adds missing `go:generate`, so all code can now be generated running `go generate ./...`
- Refresh generated files
- Update imports to the new dependency.
- `go mod tidy`

### CODE REVIEW

**Review by ericpromislow — APPROVED** [review]
Looks fine. I especially like the way the uber version writes out the command in generated files that was used to generate them.

**Comment by aruiz14** [comment]
Thanks @ericpromislow, would you mind also taking a look at the equivalent PR in [wrangler](https://github.com/rancher/wrangler/pull/468)?

**Review by moio — DISMISSED** [review]
Switching to a maintained version is a good thing (tm)

approved

**Review by moio — APPROVED** [review]

**Review by ericpromislow — APPROVED** [review]
Good after this last change

**Pull request merged**
