### PR TITLE
sql: silence informer errors on unwatchable resources

### PR DESCRIPTION
**Pull request by moio**
Listable-but-unwatchable resources such as `nodes metrics.k8s.io/v1beta1` allow an Informer to be started, but it will by default log all watch failures.

Add a boolean flag to silence those errors.

partially addresses https://github.com/rancher/rancher/issues/46030
supports https://github.com/rancher/steve/pull/284

_best reviewed commit-by-commit_

### CODE REVIEW

**Comment by ericpromislow** [comment]
Looks ok, but how is the calling code in `steve` supposed to know which resources are watchable and which aren't? I assume there's something in one of the schema packages, but haven't found it.

**Review by ericpromislow — COMMENTED** [review]
Looks ok, but I'd like to know how clients determine when `watchable` should be true.

**Comment by moio** [comment]
Yes, we have a method for that in Steve https://github.com/rancher/steve/blob/ea177193f12ade5f64ac4ef58354a629329da9e2/pkg/controllers/schema/schemas.go#L111

This PR actually supports a sister Steve PR https://github.com/rancher/steve/pull/284

**Review by ericpromislow — APPROVED** [review]
Looks good

**Pull request merged**
